name:                minimal-io
version:             0.1.0.0
github:              "Nikrolaks/minimal-io"
license:             BSD3
author:              "Nikrolaks"
maintainer:          "nikrolaks17@gmail.com"
copyright:           "Nikrolaks"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Nikrolaks/minimal-io#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  minimal-io-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minimal-io

tests:
  minimal-io-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minimal-io
